-- One-off data migration: moves the 40 static tasks from src/lib/data.ts /
-- server/src/tokens.ts into dev_challenges, using the exact same ids so
-- every existing completion/post/suggestion reference keeps resolving via
-- resolveBaseCatalogEntry (see server/src/catalog.ts). See
-- docs/task-database-roadmap.md Phase 3.
--
-- Text (title/desc) is taken from src/lib/data.ts, not the
-- server/src/tokens.ts mirror: a diff found the two had drifted on ~29 of
-- 40 desc fields, all the same shape (tokens.ts had picked up em dashes
-- that data.ts never had) — data.ts's text is both the one users already
-- see today and the one compliant with AGENTS.md's "no em dashes in
-- challenge titles/descriptions" rule. No other field (tokens, cadence,
-- cat, verify, proofType, streakTarget) differed between the two copies.
--
-- guide_checklist and verifiability_notes are deliberately left NULL /
-- flagged, not backfilled as "passing" — these 40 predate the five-test
-- guide and have not been re-reviewed against it as part of this
-- mechanical migration. Do not treat their presence here as a quality
-- endorsement.

INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-water', 'Chug a gallon of water', 'One gallon (3.8L) across the day. Photograph the empty jug.', 15, 'daily', 'fitness', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-steps', 'Hit 10,000 steps', 'Walk it out. Screenshot your step-counter app showing the total.', 15, 'daily', 'fitness', 'photo', 'screenshot', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-pushups', 'Do 20 push-ups', 'Split them up however you like. Knees are allowed. Photograph yourself mid-set.', 10, 'daily', 'fitness', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-logspend', 'Log every purchase today', 'Every coffee, every tap of the card. Screenshot your tracker at day''s end.', 10, 'daily', 'finance', 'photo', 'screenshot', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-nospend', 'Pack your own lunch', 'Skip the takeout line: make something at home and bring it. Photograph the lunch you packed.', 20, 'daily', 'finance', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-cook', 'Cook instead of ordering', 'Make dinner at home tonight. Delivery apps stay closed. Photograph the finished meal.', 15, 'daily', 'finance', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-call', 'Video call a friend or family member', 'An actual face-to-face call, five minutes or more. Screenshot it mid-conversation.', 15, 'daily', 'social', 'photo', 'screenshot', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-compliment', 'Leave an anonymous kind note for a stranger', 'Sticky note, gift receipt, whatever. Leave it somewhere it''ll be found. Photo it first.', 10, 'daily', 'social', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-reconnect', 'Write a note to someone you lost touch with', '"Hey, you crossed my mind today." Write it by hand, then photograph it before you send it.', 15, 'daily', 'social', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-coldshower', '60-second cold shower', 'End your shower cold, count to sixty, then photograph yourself right after.', 15, 'daily', 'courage', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-newstreet', 'Walk a street you''ve never walked', 'Take the unfamiliar turn on purpose. Photograph the street sign or a landmark along it.', 15, 'daily', 'explore', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-newlunch', 'Eat somewhere new', 'Even if it''s just a snack, photograph your food or the storefront.', 15, 'daily', 'explore', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-nosocial', 'No social media before noon', 'Protect your morning brain. Screenshot your phone''s screen-time app showing none before noon.', 20, 'daily', 'mind', 'photo', 'screenshot', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-lunchspot', 'Eat lunch somewhere other than usual', 'A different seat, room, or spot outside. Photograph your lunch there.', 10, 'daily', 'mind', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('d-newingredient', 'Cook with an ingredient you''ve never used', 'Something new in your kitchen tonight. Photograph the ingredient and the dish.', 10, 'daily', 'mind', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-newsport', 'Take a boxing class', 'Find a local gym offering one. Photograph yourself there or your gloves/gear.', 50, 'weekly', 'fitness', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-15k', 'Cover 15km on foot', 'Running or walking, totaled across the week. Screenshot your tracker''s weekly total.', 50, 'weekly', 'fitness', 'photo', 'screenshot', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-budget', 'Set a weekly budget & stick to it', 'Write the number Sunday, beat it by Saturday. Screenshot the final numbers.', 60, 'weekly', 'finance', 'photo', 'screenshot', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-mealprep', 'Meal prep for the week', 'Cook once, eat five times. Photograph the containers.', 50, 'weekly', 'finance', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-subs', 'Audit your subscriptions', 'List them all, cancel at least one. Screenshot the list or the cancellation.', 40, 'weekly', 'finance', 'photo', 'screenshot', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-savings', 'Move money to savings', 'Any amount, automate it if you''re feeling fancy. Screenshot the transfer.', 50, 'weekly', 'finance', 'photo', 'screenshot', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-nophones', 'Share a phone-free meal', 'One full meal with someone, devices face-down. Photograph the table with both phones face-down next to your plates.', 40, 'weekly', 'social', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-oldfriend', 'Write a real letter to an old friend', 'Handwritten, no shortcuts. Stamp it and photograph it before it goes in the mail.', 50, 'weekly', 'social', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-solo', 'See a movie alone at the theater', 'No company, on purpose. Photograph your ticket stub.', 50, 'weekly', 'courage', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-negotiate', 'Ask for a discount at checkout', 'Any store, any reason. Photograph the receipt or confirmation showing the win.', 60, 'weekly', 'courage', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-newhood', 'Find a mural or street art piece nearby', 'Somewhere in town you''ve never noticed it. Photograph it.', 60, 'weekly', 'explore', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-newcuisine', 'Try an Ethiopian restaurant', 'Order something you can''t pronounce. Photograph your dish or the menu.', 50, 'weekly', 'explore', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-tourist', 'Visit a museum or park you haven''t been to', 'One you keep meaning to check out. Photograph yourself there or your ticket.', 75, 'weekly', 'explore', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-martini', 'Learn to make an espresso martini', 'Espresso, coffee liqueur, vodka. Shake it like you mean it. Photograph the finished drink.', 40, 'weekly', 'mind', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-oldfashioned', 'Create an Old Fashioned', 'Bourbon, sugar, bitters, an orange peel. Stir, don''t shake. Photograph the finished drink.', 40, 'weekly', 'mind', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-sunset', 'Digital sunset, 5 nights', 'Screens off an hour before bed. Screenshot your screen-time app each of five nights.', 60, 'weekly', 'mind', 'streak', 'screenshot', 5, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('w-recipe', 'Cook a risotto from scratch', 'Stir it slow, get it creamy. Photograph the finished dish.', 40, 'weekly', 'mind', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('m-milestone', 'Run a 5K', 'Register for one or just time yourself. Photograph your finish, bib, or time.', 200, 'monthly', 'fitness', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('m-emergency', 'Grow your emergency fund', 'Start it or boost it. Screenshot the balance or the transfer.', 200, 'monthly', 'finance', 'photo', 'screenshot', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('m-volunteer', 'Volunteer locally', 'A few hours for your community. Photograph your sign-in sheet, name badge, or the work itself as proof.', 200, 'monthly', 'social', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('m-class', 'Take an improv comedy class', 'One session, no experience needed. Photograph yourself there.', 250, 'monthly', 'courage', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('m-speech', 'Perform at an open mic', 'Comedy, poetry, music. Sign up and go. Snap a photo right after.', 300, 'monthly', 'courage', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('m-daytrip', 'Take a day trip', 'Somewhere within two hours. Photograph yourself or the view once you get there.', 250, 'monthly', 'explore', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('m-sunrise', 'Watch the sunrise from a rooftop or hilltop', 'One early alarm, one great view from up high. Photograph the sunrise itself.', 150, 'monthly', 'explore', 'photo', 'camera', NULL, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
INSERT INTO dev_challenges (id, title, desc, tokens, cadence, cat, verify_type, proof_type, streak_target, place_lat, place_lng, radius_meters, proof_accept, proof_reject, verifiability_notes, guide_checklist, active, created_by, created_at, updated_at) VALUES ('m-skill30', '12-day skill streak', '10 minutes a day on one skill: instrument, language, code, art. Photograph or screenshot each of 12 check-ins.', 250, 'monthly', 'mind', 'streak', 'either', 12, NULL, NULL, NULL, NULL, NULL, 'Migrated from the static catalog (src/lib/data.ts) on 2026-08-06. Not yet re-reviewed against the five-test guide in docs/challenge-writing-guide.md.', NULL, 1, 'migration', 1786034453112, 1786034453112);
